src/objects/Daily_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Daily Performance</relationshipLabel>
        <relationshipName>Daily_Performance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Daily Performance</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Daily Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incentive_Plan__c.object
<CustomObject>
    <label>Incentive Plan</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Weekly_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Weekly Performance</relationshipLabel>
        <relationshipName>Weekly_Performance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Start_Date__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Performance</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Weekly Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Weekly_Temp_Calc__c.object
<CustomObject>
    <fields>
        <fullName>Calculation_Error_Message__c</fullName>
        <label>Calculation Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calculation_Status__c</fullName>
        <label>Calculation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Weekly Temp Calc</relationshipLabel>
        <relationshipName>Weekly_Temp_Calc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Bonus__c</fullName>
        <label>Total Bonus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Week_Start_Date__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Temp Calc</label>
    <nameField>
        <label>Interim Weekly Calc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Temp Calc</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncentivePayManagerTest.cls
@isTest
private class IncentivePayManagerTest 
{
	private static final String API_ENDPOINT = 'unittestendpoint';
	
    static testMethod void testWithSingleResult() 
    {
    	String mockReturnValueAsString = '10';
    	Decimal mockReturnValueAsDecimal = Decimal.valueOf(mockReturnValueAsString);
    	
    	// set up the MockCalcEngine
    	TestDataHelper.addCustomSetting(API_ENDPOINT);
    	RemoteCalcEngine.CALLOUT = new MockRemoteCalcEngine( MockRemoteCalcEngine.MockResult.ReturnSuccess, mockReturnValueAsString);
    	
    	// create an incentive plan	
    	Incentive_Plan__c ip = TestDataHelper.createIncentivePlan();
    	Date weekStartingDate = Date.valueOf('2222-01-05');
    	
    	// create some data..
    	Employee__c emp1 = TestDataHelper.createEmployee('UNIT1', 'TEST1', 100, 1);
		createEmpChildData(emp1.Id, weekStartingDate);
    	
    	Employee__c emp2 = TestDataHelper.createEmployee('UNIT2', 'TEST2', 200, 2);
    	createEmpChildData(emp2.Id, weekStartingDate);
    	
    	IncentivePayManager ipm = new IncentivePayManager(ip.Id, weekStartingDate);
    	ipm.prepareData();
    	ipm.calculateIncentivePay();
    	
    	// now verify the results
    	List<Weekly_Temp_Calc__c> answers = 
		    	[SELECT w.Week_Start_Date__c, w.Unique_ID__c, w.Total_Bonus__c, w.Name, w.Id, w.Employee__c, w.Data__c, w.Calculation_Status__c, w.Calculation_Error_Message__c 
		    	  FROM Weekly_Temp_Calc__c w
		    	 WHERE w.Week_Start_Date__c = :weekStartingDate];
		    	 
		System.assertEquals(2, answers.size());
		
		for(Weekly_Temp_Calc__c wtc : answers)
		{
			System.assertEquals('Calculated', wtc.Calculation_Status__c);
			System.assertEquals(mockReturnValueAsDecimal, wtc.Total_Bonus__c);
		}
		
    }
    
    static testMethod void testWithJsonResult()
    {
    	String mockReturnValueAsString = '[{"Calculation_Error_Message__c":null,"Calculation_Status__c":null,"Data__c":{"daily_performance__r_number_of_escalated_calls__c":45,"daily_performance__r_total_number_of_calls__c":1500,"weekly_performance__r_customer_satisfaction_percentage__c":98.3},"Employee__c":"a00E0000003wkibIAA","Total_Bonus__c":10,"Unique_ID__c":"01/05/2222-1","Week_Start_Date__c":"2222-02-05T00:00:00Z"},{"Calculation_Error_Message__c":null,"Calculation_Status__c":null,"Data__c":{"daily_performance__r_number_of_escalated_calls__c":45,"daily_performance__r_total_number_of_calls__c":1500,"weekly_performance__r_customer_satisfaction_percentage__c":98.3},"Employee__c":"a00E0000003wkicIAA","Total_Bonus__c":10,"Unique_ID__c":"01/05/2222-2","Week_Start_Date__c":"2222-02-05T00:00:00Z"}]';
    	Decimal expectedResult = 10.0;
    	
    	// set up the MockCalcEngine
    	TestDataHelper.addCustomSetting(API_ENDPOINT);
    	RemoteCalcEngine.CALLOUT = new MockRemoteCalcEngine( MockRemoteCalcEngine.MockResult.ReturnSuccess, mockReturnValueAsString);
    	
    	// create an incentive plan	
    	Incentive_Plan__c ip = TestDataHelper.createIncentivePlan();
    	Date weekStartingDate = Date.valueOf('2222-01-05');
    	
    	// create some data..
    	Employee__c emp1 = TestDataHelper.createEmployee('UNIT1', 'TEST1', 100, 1);
		createEmpChildData(emp1.Id, weekStartingDate);
    	
    	Employee__c emp2 = TestDataHelper.createEmployee('UNIT2', 'TEST2', 200, 2);
    	createEmpChildData(emp2.Id, weekStartingDate);
    	
    	IncentivePayManager ipm = new IncentivePayManager(ip.Id, weekStartingDate);
    	ipm.prepareData();
    	ipm.calculateIncentivePay();
    	
    	// now verify the results
    	List<Weekly_Temp_Calc__c> answers = 
		    	[SELECT w.Week_Start_Date__c, w.Unique_ID__c, w.Total_Bonus__c, w.Name, w.Id, w.Employee__c, w.Data__c, w.Calculation_Status__c, w.Calculation_Error_Message__c 
		    	  FROM Weekly_Temp_Calc__c w
		    	 WHERE w.Week_Start_Date__c = :weekStartingDate];
		    	 
		System.assertEquals(2, answers.size());
		
		for(Weekly_Temp_Calc__c wtc : answers)
		{
			System.assertEquals('Calculated', wtc.Calculation_Status__c);
			System.assertEquals(expectedResult, wtc.Total_Bonus__c);
		}
    	
    }
    
    private static void createEmpChildData(Id empId, Date weekStartingDate)
    {
    	// create some child data records
    	Weekly_Performance__c weeklyPerf1 = TestDataHelper.createWeeklyPerformance(empId, weekStartingDate, 98.3);
    	for(Integer i=1;i<6;i++)
    	{
    		Daily_Performance__c dailyPerf = TestDataHelper.createDailyPerformance(empId, weekStartingDate+i, 3*i, 100*i);
    	}
    }
}