src/objects/Daily_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Daily Performance</relationshipLabel>
        <relationshipName>Daily_Performance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Escalated_Calls__c</fullName>
        <label>Number of Escalated Calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Calls__c</fullName>
        <label>Total Number of Calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Daily Performance</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Daily Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Wages__c</fullName>
        <label>Total Wages</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incentive_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Data_Field_Name__c</fullName>
        <label>Data Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID_Field_Name__c</fullName>
        <label>Employee ID Field Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Function_Name__c</fullName>
        <label>Function Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incentive_Plan_Name__c</fullName>
        <label>Incentive Plan Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Data_From__c</fullName>
        <label>Use Data From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Incentive Plan</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RemoteCalcEngineCustomSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <label>API Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Remote Calc Engine Custom Settings</label>
</CustomObject>

src/objects/Weekly_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Satisfaction_Percentage__c</fullName>
        <label>Customer Satisfaction Percentage</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Weekly Performance</relationshipLabel>
        <relationshipName>Weekly_Performance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Start_Date__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Performance</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Weekly Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Weekly_Temp_Calc__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Weekly Temp Calc</relationshipLabel>
        <relationshipName>Weekly_Temp_Calc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Start_Date__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Temp Calc</label>
    <nameField>
        <label>Interim Weekly Calc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Temp Calc</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataHelper.cls
@isTest
public class TestDataHelper 
{
	
	public static void addCustomSetting(String apiEndpoint)
    {
    	User thisUser = [SELECT Id FROM User where Id = :UserInfo.getUserId() ];
    	System.runAs(thisUser)
    	{
    		RemoteCalcEngineCustomSettings__c rcecs = new RemoteCalcEngineCustomSettings__c();
    		rcecs.API_Endpoint__c = apiEndpoint;
    		
    		insert rcecs;	
    	}
    }
    
	public static Incentive_Plan__c createIncentivePlan()
	{ 
		Incentive_Plan__c ip = new Incentive_Plan__c();
		ip.Data_Field_Name__c = 'Data__c';
		ip.Employee_ID_Field_Name__c = 'Employee_ID__c';
		ip.Function__c = 'function calcBonus(weeklytempcalc) { return 10; }';
		ip.Function_Name__c = 'calcBonus';
		ip.Incentive_Plan_Name__c = 'UNIT TEST Incentive Plan';
		ip.Use_Data_From__c = 'Weekly_Temp_Calc__c';
		
		insert ip;
		
		return ip;
	}
	
	public static Employee__c createEmployee(String firstName, String lastName, Decimal wages, Decimal externalEmpId)
	{
		Employee__c emp = new Employee__c();
		emp.Employee_ID__c = externalEmpId;
		emp.First_Name__c = firstName;
		emp.Last_Name__c = lastName;
		emp.Total_Wages__c = wages;
		
		insert emp;
		
		return emp;
	}
	
	public static Weekly_Performance__c createWeeklyPerformance(Id empId, Date weekStartDate, Decimal custSatPct)
	{
		Weekly_Performance__c weekPerf = new Weekly_Performance__c();
		weekPerf.Employee__c = empId;
		weekPerf.Customer_Satisfaction_Percentage__c = custSatPct;
		weekPerf.Week_Start_Date__c = weekStartDate;
		
		insert weekPerf;
		
		return weekPerf;
	}
	
	public static Daily_Performance__c createDailyPerformance(Id empId, Date aDate, Decimal numEscalatedCalls, Decimal numTotalCalls)
	{
		Daily_Performance__c dailyPerf = new Daily_Performance__c();
		dailyPerf.Employee__c = empId;
		dailyPerf.Date__c = aDate;
		dailyPerf.Number_of_Escalated_Calls__c = numEscalatedCalls;
		dailyPerf.Total_Number_of_Calls__c = numTotalCalls;
		
		insert dailyPerf;
		
		return dailyPerf;
	}
}