src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Total_Wages__c</fullName>
        <label>Total Wages</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Incentive_Plan__c.object
<CustomObject>
    <label>Incentive Plan</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Proxy__c.object
<CustomObject>
    <description>Lookup field proxy object</description>
    <fields>
        <fullName>Incentive_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive Plan</label>
        <referenceTo>Incentive_Plan__c</referenceTo>
        <relationshipLabel>Proxies</relationshipLabel>
        <relationshipName>Proxies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Starting_Date__c</fullName>
        <label>Week Starting Date</label>
        <type>Date</type>
    </fields>
    <label>Proxy</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Proxy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proxies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Weekly_Temp_Calc__c.object
<CustomObject>
    <fields>
        <fullName>Calculation_Error_Message__c</fullName>
        <label>Calculation Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calculation_Status__c</fullName>
        <label>Calculation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Weekly Temp Calc</relationshipLabel>
        <relationshipName>Weekly_Temp_Calc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Bonus__c</fullName>
        <label>Total Bonus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Week_Start_Date__c</fullName>
        <label>Week Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Temp Calc</label>
    <nameField>
        <label>Interim Weekly Calc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Temp Calc</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncentivePayController.cls
public with sharing class IncentivePayController 
{
	public Proxy__c proxy { get; set; }
	public List<Weekly_Temp_Calc__c> results { get; set; }
	public Boolean haveResults { get { return results.size() > 0; } }
	public Boolean preparedData { get; set; }
	public Boolean calculatedResults { get; set; }
	
	private IncentivePayManager incentivePayMgr; 
	
	public IncentivePayController()
	{
		results = new List<Weekly_Temp_Calc__c>();
		proxy = new Proxy__c();
		proxy.Week_Starting_Date__c = getPriorSunday();
		preparedData = false;
		calculatedResults = false;		
	}
	
	public PageReference prepareData()
	{
		try
		{
			incentivePayMgr = new IncentivePayManager(proxy.Incentive_Plan__c, proxy.Week_Starting_Date__c);
			incentivePayMgr.prepareData();
			
			preparedData = true;
		}
		catch(Exception ex)
		{
			System.debug('There was a problem calculating the incentive pay. '+ex.getMessage());
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'An error occurred while processing your request. '+ex.getMessage()+'\n'+ex.getStackTraceString()));
		}
		 			
		return null;		
	}
	
	public PageReference calculate()
	{
		try
		{
			incentivePayMgr.calculateIncentivePay();
			
			calculatedResults = true;
		
			results = [SELECT w.Week_Start_Date__c, w.Unique_ID__c, w.Total_Wages__c, w.Total_Bonus__c, w.Name, w.Id, w.Employee__c, w.Data__c, w.Calculation_Status__c, w.Calculation_Error_Message__c 
			  			 FROM Weekly_Temp_Calc__c w
			 			WHERE w.Week_Start_Date__c = :proxy.Week_Starting_Date__c];
		}
		catch(Exception ex)
		{
			System.debug('There was a problem calculating the incentive pay. '+ex.getMessage());
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'An error occurred while processing your request. '+ex.getMessage()+'\n'+ex.getStackTraceString()));
		}
		 			
		return null;
	}
	
	private Date getPriorSunday()
	{
		Date aDate = Date.today();
		// note this is locale specific
		// US locales will return a Sunday. 
		// European Locales will return a Monday.
		return aDate.toStartOfWeek();
	}
}